# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rich Tremblay
title: GC Cloud One Product Owner
email: richard.tremblay@ssc-spc.gc.ca
#website: tremblr.github.io

# Social links
#twitter_username: richtremblay
#github_username:  tremblr
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rich Tremblay.  I am a IT professional, with a background in IT/Cyber security (10 years), and solution architecture (10+ years). My current work in SSC's Cloud team has allowed me to combine my passions for technology transofrmation, but also for business and process tranformation.  To work in deisgning and building modern digital platforms in a client-focused and modern manner is a dream job. 
  
  I have passion for teamwork, innovation and exploring new technologies and methodologies. 
 
# Projects Section
projects_title: Skills

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in IT, some of my other interests and hobbies are:
   - Spending time with my family
   - Analog Gaming (Boardgames)
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
