# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Rich Tremblay
title: Senior Advisor (CS-04)
email: richard.tremblay@canada.ca
#website: tremblr.github.io

# Social links
#twitter_username: richtremblay
#github_username:  tremblr
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/avatar.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rich Tremblay.  I am a IT professional, with a background in IT/Cyber security, server administration and solution architecture. Before my current assignment to the Quality Management Program (QMP) initiative to examine enterpise process improvements,  I specialed in integrated solution architecture for SSC and clients.
  
  I have passion for teamwork, innovation and exploring new technologies and methodologies.  I have an extensive background in <mark>SSC Service Offerings</mark>, <mark>Workload Migration</mark> , <mark>GC design patterns</mark> , and <mark>GoC security processes</mark> and <mark>Enterprise Architecture principles</mark>.
  
  My current goal is to expand my skill-set and explore futher cloud technologies, automation and modern delivery methodologies like DevSecOps and Design Thinking.

# Projects Section
projects_title: Skills

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in IT, some of my other interests and hobbies are:
   - Spending time with my family
   - Analog Gaming (Boardgames)
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
